### PR TITLE
Update tags

### PR DESCRIPTION
**Pull request by tfoote**
After [some discussion](https://robotics.meta.stackexchange.com/questions/1443/tagging-ros-questions-with-versions). I've removed the no-version-declared

I also alphabetized, deduplicated, reduced tags to the top ones that have about 10 or more tags. As well as reducing it to the top 1000 or so tags.

### CODE REVIEW

**Comment by Crola1702** [comment]
For proposed_gazebo_tags.csv I see a message in GitHub UI
> *We can make this file beautiful and searchable if this error is corrected: It looks like row 134 should actually have 2 columns, instead of 3. in line 133.*

Same for proposed_ros_mappings.csv I see:
> We can make this file [beautiful and searchable](https://docs.github.com/articles/rendering-csv-and-tsv-data) if this error is corrected: It looks like row 4 should actually have 3 columns, instead of 2. in line 3.

Also, I don't fully understand the new format of ros_mappings:

```
1.gazebo,gazebo,ros
1.indigo,ros-indigo,ros
1.navigation,navigation,ros
```

I see 3 columns, and the last one is always `ros`, how should I handle these? Some kind of prefixes?

Thanks for pushing this tags effort!

**Comment by tfoote** [comment]
The first column is the tag to match, and the following list are the tags to apply. For any given tag there may be one or more resultant tags.

> I see 3 columns, and the last one is always ros, how should I handle these? Some kind of prefixes?
Because all things are coming from ros answers for this file they should have the ros tag. 

So for the first one from the ros file, if it has "gazebo" on ros answers, then tag it "gazebo" and "ros"

We'd talked about this being implicit in your script doing the migration, but I figured it would be easier to apply here. However now that I think about it. Anything w/o a tag should still get ros, so you probably need a special logic anyway. 

There's the 2nd file for gazebo now too. I guess I should just trim off the ros tags and leave it like gazebo w/o it manually flooded. Does that make sense to you?

**Comment by Crola1702** [comment]
> Does that make sense to you?

Sure! I was trying the new approach and have some results already:


<details>

<summary>

#### Some Gazebo tags

</summary>

Original Tags | Mapped Tags
-- | --
['gazebo', 'sdf'] | ['sdformat', 'gazebo']
['gazebo-2', 'error'] | ['ros']
['gazebo-7', 'ros-kinetic', 'contact_sensor'] | ['ros-kinetic', 'gazebo-7']
['coordinate', 'link', 'frame'] | ['ros']
['transmission', 'gazebo-ros-control'] | ['ros']
[] | ['ros']
['ros-kinetic', 'gazebo-7', 'rosservice', 'python'] | ['ros-kinetic', 'python', 'gazebo-7']
['gazebo7', 'protobuf'] | ['gazebo-7']
['api', 'polarisrangerev', 'Intermediate'] | ['ros']
['gazebo', 'xacro', 'URDF', '4-wheel', 'diff-drive'] | ['xacro', 'differential-drive', 'gazebo']
['gazebo', 'kinetic', 'tf'] | ['transforms', 'ros-kinetic', 'gazebo']
['kinect', 'gazebo-7'] | ['kinect', 'gazebo-7']
[] | ['ros']
['MoveIt', 'ros-kinetic', 'gazebo-7'] | ['ros-kinetic', 'gazebo-7']
[] | ['ros']
['MoveIt', 'gazebo-7', 'ros-kinetic'] | ['ros-kinetic', 'gazebo-7']
['subscriber', 'publisher', 'node'] | ['ros']
['ROS', 'ros_fuerte', 'ros_gazebo', 'xacro', 'URDF'] | ['ros_gazebo', 'ros', 'ros-fuerte', 'xacro']
['simulator_gazebo', 'gazebo-1.5', 'groovy', 'model'] | ['gazebo-model', 'groovy', 'gazebo-1.5', 'gazebo']
['gazebo', 'groovy', 'gazebo_plugins', 'skid-steer'] | ['skid-steer', 'groovy', 'gazebo', 'gazebo-plugin']
['rospy', 'python', 'drcsim', 'installation', 'Ubuntu12.04'] | ['python', 'drcsim', 'installation', 'rospy']
['skid-steer', 'model', 'include', 'sdf', 'plugin'] | ['skid-steer', 'gazebo-model', 'gazebo-plugin', 'sdformat']

</details>

For ROS we're skipping some tags because SE supports maximum 5 tags per questions (according to Adam's requirements). 

We skip an average of 0.1 tags per question, nothing that I think we should worry about

<details>

<summary>

#### Some ROS tags

</summary>

Original Tags | Mapped Tags
-- | --
['ros2', 'crystal', 'gazebo'] | ['ros2', 'ros', 'gazebo', 'ros-crystal']
['melodic', '_tf2', 'rtabmap'] | ['rtabmap', 'ros', 'ros-melodic', 'slam', 'navigation']
['rqt_graph', 'fedora29', 'pydot', 'ImportError', 'kinetic'] | ['rqt_graph', 'ros', 'ros-kinetic']
['kinetic', 'nav2d', 'operator', 'Clearpath', 'Husky', 'ssh'] | ['ros', 'ssh', 'clearpath', 'husky', 'nav2d']
['indigo', 'ubuntu14.04', 'anaconda'] | ['ros', 'ubuntu-trusty', 'ubuntu', 'anaconda', 'ros-indigo']
['kinetic', '1.gazebo', '4.RViz', 'cmd_vel.linear.x'] | ['ros', 'gazebo', 'ros-kinetic', 'rviz']
['kinetic', 'all_topics', '1.gazebo', 'rviz', 'summit_xl', 'Summit', 'Robotnik', 'gazebo', 'navigation', 'control', 'controller', 'move', 'tf', 'transformation'] | ['ros', 'transforms', 'rviz', 'control', 'transform']
['navigation', 'kinetic', 'localization', 'gps', 'odometry'] | ['ros', 'gps', 'localization', 'odometry', 'navigation']
['kinetic', 'freenect', 'Kinect', 'jpeg', 'compressedImage', '16UC1', 'decompress'] | ['ros', 'freenect', 'kinect', 'compressedimage', 'ros-kinetic']
['cuda', 'ROS', 'kinetic', 'opencv', 'gpu', 'Ubuntu', 'ubuntu-16.0.4'] | ['ros', 'ubuntu', 'opencv', 'cuda', 'gpu']
['Catkin-build', 'full-install#ros#4.ubuntu-16.04', 'kinetic'] | ['catkin', 'ros', 'ros-kinetic']
['1.gazebo', '4.RViz', 'kinetic', 'kinetic-gazebo7'] | ['ros', 'gazebo', 'ros-kinetic', 'rviz']
['keyboard_teleop', 'turtlebot', 'turtlebot_simulation', 'turtlebot_teleop', 'kinetic', 'gazeboRviz', 'gazebo'] | ['ros', 'rviz', 'gazebo', 'turtlebot', 'keyboard_teleop']
['ros2', 'colcon', 'geometry_msg'] | ['colcon', 'ros2', 'ros']
['kinetic', 'quaternion', 'pose', 'orientation', 'moveit'] | ['ros', 'moveit', 'pose', 'ros-kinetic', 'quaternion']
['action_client', 'action_server', 'action_server_client', 'actionlib', 'feedback', 'simple_action_client', 'kinetic', 'ROS1'] | ['ros', 'actionlib', 'action_client', 'action_server', 'ros-kinetic']
['kinetic', 'namespace', 'roswtf'] | ['ros', 'namespace', 'ros-kinetic', 'roswtf']
['ros2', 'turtlesim', 'simulator'] | ['ros2', 'ros', 'simulation', 'turtlesim']
['kinetic'] | ['ros', 'ros-kinetic']


</details>

**Comment by tfoote** [comment]
Overall that looks good. However we should have the gazebo questions apply `gazebo` as the default tag not `ros`

In [e46d270](https://github.com/osrf/se_migration_tags/pull/1/commits/e46d2701a11e75811c49c6932bcec0d7d1704043) I've removed the appended `ros` from the ROS csv so that you can use the same default behavior as here: 

```
        if not 'ros' in elements[1:]:
            elements.append('ros')
```

But for the gazebo export use `gazebo` instead of `ros`

**Comment by tfoote** [comment]
I'm going to merge this if there's more suggestions lets do it in another PR

**Pull request merged**
